package com.wave.backend.constant;

public enum UserServiceStatus {
    USER_ALL_OK,
    USER_NOT_EXIST,
    USER_ALREADY_EXIST,
    USER_ACCOUNT_ILLEGAL,
    USER_PASSWORD_ILLEGAL,
    PASSWORD_NOT_MATE_REPEAT_PASSWORD,
    USER_ACCOUNT_PASSWORD_NULL,
    USER_BEEN_BANNED,
    USER_UNKNOWN_ERROR,
    USER_EMAIL_ILLEGAL
}
