spring:
  application:
    name: ebook
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebook
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        enabled: true
        max-idle: 20
        min-idle: 0
        max-active: 20
        max-wait: -1
    connect-timeout: 3000
server:
#  port : 8443
  port: 8080
#  ssl:
#    key-store: tomcat.keystore
#    enabled: true
#    key-alias: tomcat
#    key-store-password: 123456
#    key-store-type: PKCS12


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



